### ISSUE TITLE
Numerous texture problems across multiple games

### ISSUE THREAD

**Issue by cyro666** [iXit/Mesa-3D#113]
Setup: Intel Core 2 Duo (quad), 4GB RAM, Radeon HD4890
OS: Arch Linux, your Live CD, and Ubuntu

So, I decided to check the Live CD you guys have. After enabling the native Direct3D feature I tried running NFS:Underground2. This is what I got:
![screenshot from 2015-07-02 09-58-18](https://cloud.githubusercontent.com/assets/13151680/8479335/754f4ba2-20d7-11e5-95b4-cf5a8cb50a8d.png)

As you can see, the spectator's textures are stretched all over the place. After driving for a while, I noticed the asphalt textures weren't right as well. Also, the sea doesn't look right as well:
![screenshot from 2015-07-02 09-58-25](https://cloud.githubusercontent.com/assets/13151680/8479401/dbed311c-20d7-11e5-8da9-b0d42d989ee6.png)

On the plus side, native Direct3D is working, the performance was MUCH better, even though DRI2 was being used. After that, I thought it must have been a problem with that game. But no... I tried Oblivion:

![screenshot from 2015-07-02 10-01-19](https://cloud.githubusercontent.com/assets/13151680/8479435/175a6238-20d8-11e5-9ed5-313fb7b79304.png)

![screenshot from 2015-07-02 10-01-41](https://cloud.githubusercontent.com/assets/13151680/8479445/28c144c4-20d8-11e5-941c-7ca4af181b0d.png)

What about Jade Empire?

No text in menus:
![screenshot from 2015-07-02 10-02-36](https://cloud.githubusercontent.com/assets/13151680/8479459/3f2cfcf8-20d8-11e5-9a44-f9373f91bf98.png)

Ugh, that's definitely wrong:
![screenshot from 2015-07-02 10-03-08](https://cloud.githubusercontent.com/assets/13151680/8479480/590e1288-20d8-11e5-853a-540c61a4e723.png)

I though, maybe it was a problem with the version on the Live CD. So I went and built myself all the PKGBUILDs for my Arch installation (wine, mesa, xf86-video-ati), the ones lyonsb mainains. But the problems were identical, no change. Even after using DRI3. I even tried different Mesa packages - I tried building the ones you get with the distro with DRI3, but there was no change.

Same thing on Ubuntu, I used oibaf and sarnex's PPAs, no difference, same textures.

In the end, I tried Portal. And it actually worked well, except for one issue. The glass walls aren't visible. There were supposed to be glass walls directly in front of me, but aren't visible:
![screenshot from 2015-07-02 16-02-28](https://cloud.githubusercontent.com/assets/13151680/8479650/713f4d12-20d9-11e5-8229-2c5c8e206cbc.png)

And subtitle text isn't quite alright, but that's a minor issue.

**Comment by axeldavy** [comment]
I believe there may be some driver bugs in there.
Portal glass walls are quite visible for me (but I use an SI card, not R600).

The NFS2 bug seems to be vertex coordinates being wrong. Either driver bug, or gallium nine emulating improperly a d3d9 instruction (unlikely if that works with wine, since we do the same that wine now).

Jade Empire seems to have wrong culling (you see inside instead of outside), and it may be game setting invalid values, and we have hard time trying to know how we should default to invalid values.

If you are interested to help debugging the games, we'd be interested in traces made with apitrace, and in logs (mesa built with debug info + NINE_DEBUG=all). Don't hesitate to come on our irc channel too (#d3d9 on freenode)

**Comment by cyro666** [comment]
I will, definitely! Although no game worked as it should, I was still amazingly impressed by the performance gain. So, next week when I have access to that machine again.

**Comment by farmboy0** [comment]
I have uploaded a trace file that shows the issue of disapearing text in Jade Empire.
the file is called JadeEmpire.trace.gz on the ftp server.

**Comment by axeldavy** [comment]
Someone has investigated a few days ago some bugs similar to these ones, and it seems r600g driver has buggy behaviour that wasn't triggered with typical opengl shaders.

The fix should land soon.

**Comment by farmboy0** [comment]
I am on radeonsi so at least the Jade Empire bug is not the r600g driver's fault.

**Comment by axeldavy** [comment]
We have a Jade Empire trace for the menu bug.
Could we get a trace of the second bug as well ?

**Comment by siro20** [comment]
Most bugs should be fixed already. Can you please test again and list the remaining issues with latest ixit git ?

**Comment by cyro666** [comment]
Is the Gallium Nine Test PPA on Ubuntu adequate (ppa:oibaf/gallium-nine)? Or should I compile my own? 

Anyways, with the one in the PPA, NFS:U2 works great. People in Jade Empire are still graphically glitched. In Oblivion, the graphical glitches are gone. The world looks great, but text and HUD are still wrong. The glass in Portal is still missing and the text is also kind of wrong.

I can post screens once I know the version I'm using is alright.

**Comment by sarnex** [comment]
If you want ixit/mesa, use my ppa ppa:commendsarnex/ixitmaster, it's mesa
git merged with ixit master.

**Comment by siro20** [comment]
I tried portal and the walls are visible for me on lastest ixit git using r600.

**Comment by cyro666** [comment]
This is my card:
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV790 [Radeon HD 4890]

Portal works exactly the same way it worked before. No glass walls. Text is still wrong:
![screenshot from 2015-12-25 13-29-21](https://cloud.githubusercontent.com/assets/13151680/12003124/da5b6136-ab13-11e5-95e7-df1f0c91c9be.png)
![screenshot from 2015-12-25 13-40-03](https://cloud.githubusercontent.com/assets/13151680/12003125/dff34866-ab13-11e5-84d6-27d21d00349a.png)
![screenshot from 2015-12-25 13-41-43](https://cloud.githubusercontent.com/assets/13151680/12003127/ecc1b7d0-ab13-11e5-940d-4fae50042a1d.png)
![screenshot from 2015-12-25 13-42-27](https://cloud.githubusercontent.com/assets/13151680/12003129/eed5aac2-ab13-11e5-9287-500af3d81cd7.png)

Jade Empire. The menus work as they should. People are still glitched:
![screenshot from 2015-12-25 13-43-40](https://cloud.githubusercontent.com/assets/13151680/12003136/01877d3a-ab14-11e5-8050-fc2eba489300.png)

Oblivion. I installed a completely vanilla version just for testing. The world looks ok so far, but the HUD and menus are still wrong:
![screenshot from 2015-12-25 13-59-58](https://cloud.githubusercontent.com/assets/13151680/12003138/20942a70-ab14-11e5-8492-40f47aa6c5da.png)

![screenshot from 2015-12-25 14-02-12](https://cloud.githubusercontent.com/assets/13151680/12003140/25a35176-ab14-11e5-9cf2-5d09c7f020d6.png)

As you can see, there's the "hotkey" and "region name text", the sneak and target health icons shouldn't be visible, etc...

Also, later I put all the settings to max and there might be an issue with the shadows on people, but it also might just be the game, not sure:
![screenshot from 2015-12-25 14-25-08](https://cloud.githubusercontent.com/assets/13151680/12003151/60701956-ab14-11e5-8fbc-19f2cfdd1b80.png)
![screenshot from 2015-12-25 14-04-41](https://cloud.githubusercontent.com/assets/13151680/12003152/68ae0bf0-ab14-11e5-8937-55c7118c0d63.png)

NFSU2 works great. I've also tried Dark Messiah of Might and Magic. It looks and works alright (HL2 engine, after all), but I've had crashes with some patches and with other versions, the game didn't start at all... Might play with that around and report a bug if I find the time.

**Comment by axeldavy** [comment]
We'd appreciate traces showing the above problems.
That way we can test several potential fixes easily.

**Comment by axeldavy** [comment]
Thanks for the oblivion trace.

For the Hotkey text issue, it looks like wine has has recently a regression that introduced the bug.
I put the link here, perhaps that's gonna help.
https://bugs.winehq.org/show_bug.cgi?id=39752

**Comment by siro20** [comment]
Tested Portal with AMD RV770 [Radeon HD4850] (DRM 2.43.0, LLVM 3.7.0)
I tried to use lots of different settings, but it was working every time. The glass is always visible.
It could be a special bug related to RV790, but it's unlikely.
Have you tried to use another GPU ?

**Comment by axeldavy** [comment]
oblivion is fixed now.

Any other bug remaining ? Closing ?

**Comment by axeldavy** [comment]
I think everything is fixed in this bug report.
