### ISSUE TITLE
RIFT image shown black: Fixed function, D3DFMT_A8

### ISSUE THREAD

**Issue by Oblit03** [iXit/Mesa-3D#200]
**Continuation of frame 0 bug discussed in issue #199.**

RIFT image is shown black in-game and in traces taken through wine on nine and wined3d. It is supposed to appear at frame 0 of the wine traces, but does not.

**Traces:**
[Nine](https://mega.nz/#!6o0wWJjZ!nJMqfhz8HYUS1C0BNHVTvxPo4X59r_qczKRpMV7rAv4)
[wined3d](https://mega.nz/#!XwMyGQ4Q!aVeJoEgmggXDKXz-KCKvJz77PGtjX6WtQVu1GNhI-js)
[Windows](https://mega.nz/#!yo8WjZzK!4DrNRmFpDDXtWfE9V4HAqqOX58dsrLmMhm1M-rBgIBc) (Image is shown under nine, wined3d and windows)
**Log:**
[RIFT](https://mega.nz/#!KtN0RKwI!vri7sjZxFBSBGJJKZ-z2rQ8CneQgM9UBpnRl-pXSuxc)

**Setup:**
Kubuntu 15.10 (64-bit)
Kernel 4.2.0-34
Wine 1.9.5 (32-bit) (Staging/Nine) (Tested with 1.9.6 as well)

**Hardware:**
Intel i7-3770
Asus P8Z77-M
Radeon HD6950 2GB (Asus)
16 GB RAM

**Comment by Oblit03** [comment]
This appears to have been fixed by a game patch. Frame 0 image and video scenes are now shown correctly.

**Files:**
[Nine-Trace](https://mega.nz/#!u0tRTITY!hjvXQEx6deOG2bnouf8P8lY2QyFttNgPgzdAModQf0Q)
Image is shown in calls 27065, 27066, 27067 and 27068.
[Nine-Log](https://mega.nz/#!PoMW3SYB!P2IvXEqm5dwHx74b0_ofnV7WjejsGTQC9p4VWub8zOQ)

**System:**
Kubuntu 15.10 (64-bit)
Radeon HD6950

**Kernel Versions:**
4.2.0-34
4.2.0-42

**Wine Versions:**
Wine 1.9.5-staging (Same version used in previous post)
Wine 1.9.13-nine (Sarnex Wine PPA / Wine Compiled from iXit Wine git) 

**Mesa Versions:**
With and without Oibaf PPA
[iXit Mesa git](https://github.com/iXit/Mesa-3D/tree/b0f42e3c446ba37b513ac6e388ff229b9dc0769c) + [Mesa git](https://cgit.freedesktop.org/mesa/mesa/commit/?id=e7d96e7685e911b91ce048c6639a4c290faf5d06)
iXit Mesa git 11.2.0 (Compiled 27/02/16)

Shall we close this?

**Comment by axeldavy** [comment]
Weird.

Are you sure it is a game patch, and not something we fixed on our side ?

**Comment by Oblit03** [comment]
I went through the previous mesa/wine/kernels used at the time of the report and the image is shown on all of them. I even ppa-purged the oibaf PPA to try and exclude other lib changes, yet it is still shown regardless of mesa version used.

I have no idea why it now works.

The frame 0 image is shown correctly in the calls listed, instead of the previous grey alpha channel images shown before. All in-game cutscene videos now appear, where they were also black before (audio still played).

The game is going for a 64-bit client though, so they might have changed things.

**Comment by Oblit03** [comment]
Another game patch just came through and it has been broken again.... Nine and WineD3D both show nothing. 
No system updates have come through since the last test.

I will post another trace+log to compare with the previous set.

**Comment by Oblit03** [comment]
This is most likely not a Nine bug, if there even is a bug. I've discovered that the wine bottle was missing d3dcompiler_43. 
This report is most likely useless and is the result of my own incompetence.

I shall ensure this does not happen again.

I apologise for any time wasted.

**Comment by axeldavy** [comment]
Ok, then I close the bug. If it happens to not be d3dcompiler_43, then we can open it again.

**Comment by Oblit03** [comment]
There may actually be a bug somewhere as this still appears in the log:
`nine:nine_state_copy_common_all: Fixed function state not handled properly by StateBlocks.`

The only visual bugs I've seen so far are also present with WineD3D, so I'm not sure what this might cause. 

**Logs:**
[FF-State](https://mega.nz/#!r4EmEA5J!mqzDhTPaTdCS8fsWcZy6BX5BPhrcoUasubvsl2XhXx8) (Cut shortly after it appears, which is about the same time as the RIFT image does. Log is already 107k lines.)
[FF-State Full](https://mega.nz/#!HhET0SgL!CLxv8CyAwUpVGeR7TUjzCrMfM9bjv8i_qLPH3fkhHAE) (VERY LARGE)
